### PR TITLE
add wagtail 26 and 27 to tested versions

### PR DESCRIPTION
**Pull request by thenewguy**
fixes issue #70

### CODE REVIEW

**Comment by zerolab** [comment]
These are great, @thenewguy. The test failure is fixed in #63 and my gut feeling is to fold your changes into that PR and commit them together

**Comment by thenewguy** [comment]
@zerolab Glad to hear it.  Are you referencing https://github.com/torchbox/wagtailmedia/pull/69 and https://github.com/torchbox/wagtailmedia/pull/67 as well?  Do you want me to make a PR that includes those and #63 with a version increment?

**Comment by zerolab** [comment]
@Chris-May incorporated your PR in #63 
Will have a look at the other two tomorrow, if that is ok

**Comment by thenewguy** [comment]
Superseded by #63

**Pull request closed without merging**
