### PR TITLE
Fix issues 100 106

### PR DESCRIPTION
**Pull request by thenewguy**
Fixes issue #100 and #106

### CODE REVIEW

**Comment by zerolab** [comment]
@thenewguy does correctly point out that all major encoders deal with fractional time. e.g. https://ffmpeg.org/ffmpeg-utils.html#time-duration-syntax

Given float is backward compatible with int, I feel we can combine this with #108. @thibaudcolas ?

**Comment by thenewguy** [comment]
@zerolab @thibaudcolas I believe we resolved this discussion in slack.  Are we ready to merge?

**Comment by zerolab** [comment]
@thenewguy :shipit:!
Can you add an upgrade consideration note in the changelog (i.e. to format the float in templates, if using it)

**Comment by thenewguy** [comment]
Changelog modified. Ready for review

**Comment by zerolab** [comment]
I've rebased and manually merged in d69c3608

Thank you for the hard work and perseverance @thenewguy !

**Pull request closed without merging**
