### PR TITLE
Add tag filter based on wagtail-images

### PR DESCRIPTION
**Pull request by th3hamm0r**
I basically synced the code with `wagtail.images`:

- `wagtailmedia/templates/wagtailmedia/media/index.html` with https://github.com/wagtail/wagtail/blob/main/wagtail/images/templates/wagtailimages/images/index.html
- `wagtailmedia/views/media.py` with https://github.com/wagtail/wagtail/blob/main/wagtail/images/views/images.py
Here I moved the search-part above the filtering, similar to wagtail-images, which avoided an error during my tests with a wagtail installation.

### CODE REVIEW

**Comment by th3hamm0r** [comment]
I missed the chooser modal, so I will try to add that code too.

**Comment by th3hamm0r** [comment]
Done. Tests are OK. Fortunately, some parts of the tag logic (e.g. JS) were already present, I just added all the missing parts (hopefully).

**Comment by zerolab** [comment]
Thank you for this @th3hamm0r. Will aim to review it today.
If you rebase on `main` that should take care of the test failures (relates to https://github.com/torchbox/wagtailmedia/commit/cffc9e8a7daa9e4e0ea5a6fb29daad4f5a0dfb43)

**Comment by zerolab** [comment]
Hey @th3hamm0r I've checked the PR and the changes make sense to me.
if you could rebase it on `main` for the testsuite to run, we can get it in. Thank you

**Comment by th3hamm0r** [comment]
Thanks for your reply @zerolab, I will be back in office the coming week, I will rebase it then as soon as possible.

**Comment by zerolab** [comment]
rebased and merge manually. Thank you @th3hamm0r th3hamm0r

**Pull request closed without merging**
