### PR TITLE
Support Wagtail 2.0 and Django 2.0

### PR DESCRIPTION
**Pull request by Rotund**
There are still 2 test failures that I believe has something to do with the way WAGTAIL_USAGE_COUNT_ENABLED was changed in Wagtail 2.0. Otherwise, all tests pass.

### CODE REVIEW

**Comment by nimasmi** [comment]
Thanks @Rotund. In general it's a good idea that we make this compatible with Wagtail 2.0, so these changes are welcome.

However, because this is a small module with limited development activity we could instead wait until Wagtail 2.0 is out, and then release a version that is compatible with that only. This would remove the need for all the `try … except` blocks and version number checking, and would keep this module tidier.

What do others think? I'm ambivalent here.

**Comment by Rotund** [comment]
Personally, I think you should have at least a version that straddles the change. I'd suggest you have a version that at least works on the last wagtail LTS (1.12) and the next wagtail LTS (is there a cadence?). Then, you can make a new version that drops 1.12 support and supports the next LTS and newer.

**Comment by Rotund** [comment]
Also, I'd love some help fixing the few admin tests that fail on Wagtail 2.0rc1.

**Comment by rvdrijst** [comment]
Now that Wagtail 2.0 has officially been released, is there anything holding this back? Would love to start using Wagtail 2.0 with this plugin 😇

**Comment by nimasmi** [comment]
No barriers from my point of view. I'm happy to review and accept a merge request, with or without the version checks. I don't have time to work on it at the moment, but I may do in the next two weeks.

**Comment by Chris-May** [comment]
@Rotund, I'm getting an error from `wagtailmedia/blocks.py`, from line 5. Should be an easy fix, and I haven't been able to figure out how to help.
> ImportError: No module named 'wagtail.wagtailcore'

**Comment by Rotund** [comment]
It's now wagtail.core

**Comment by Rotund** [comment]
Need to do a check around the import to try one and then try other on an
ImportError

**Comment by bbusenius** [comment]
@Rotund @Chris-May I put in a pull request that addresses the ImportError. This was affecting our site too.

**Comment by Rotund** [comment]
Yes, please. I must've missed one.

**Comment by bbusenius** [comment]
Yes, it was just one, as far as I know. The pull request is here: https://github.com/Rotund/wagtailmedia/pull/1. @Rotund if you accept the pull request I think it will just be appended to your pull request for torchbox automatically.

**Comment by jeromelebleu** [comment]
Please consider https://github.com/Rotund/wagtailmedia/pull/2, it fixes tests by adding the usage counter manually - as it is done by `documents` and `images`.

**Comment by v9Chris** [comment]
Any ETA when this might  make it in @nimasmi ?

**Comment by nimasmi** [comment]
Good question. Thanks for the nudge.

I've been busy on project work at work, and therefore only following along here, rather than actually looking at the work. I originally got the impression from the updates above that this was WIP, or not ready for some other reason. If you think it's ready for review, then I can look at it.

Thanks all for the contributions so far.

**Comment by jeromelebleu** [comment]
@nimasmi I'm using this branch for some projects with Wagtail 2.0 and Django 2.0, all is working fine.

**Comment by sewagodimo** [comment]
this line needs to be updated:
from wagtail.wagtailcore.blocks import ChooserBlock
https://github.com/Rotund/wagtailmedia/blob/master/wagtailmedia/blocks.py

**Comment by sewagodimo** [comment]
Hey, the most recent version of wagtailmedia 0.15 gives me the following bug: 

> ImportError: No module named 'wagtail.wagtailcore'

**Comment by Rotund** [comment]
I pulled in the most recent updates and now all tests pass. Can this be merged now?

**Comment by nimasmi** [comment]
Thanks @Rotund and @jeromelebleu. This has now been merged and released as part of v0.2.0.

**Pull request merged**
