### PR TITLE
Tidy ups for Wagtail 4

### LINKED ISSUE #46: Sort by "Uploaded" does not work
On the main list view, nothing happens when clicking "Uploaded" to change the sorting order.

uploaded-sort

I think this would be the same issue as https://github.com/wagtail/wagtail/issues/5191.

### LINKED ISSUE #47: Sorting does not work in chooser modal listing
Related: #46, https://github.com/wagtail/wagtail/issues/5191.

In the chooser modal, clicking the "title" or "uploaded" table headings takes the user to the `/admin/media/` listing view. It should instead sort directly within the modal.

chooser-sort

### LINKED ISSUE #167: Wagtail 4.0 UI Issues
### Issue Summary

Everything works basically, but I have found some obvious UI issues:

1. Text-size on wagtail's dashboard:
wagtailmedia_wagtail_home_issue

2. The list view's header looks partially unstyled:
wagtailmedia_listview_header
compared to images:
wagtail_images_listview

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Integrate `wagtailmedia`

### Technical details

* Python version: 3.10
* Django version: 4.1
* Wagtail version: 4.0rc1
* `wagtailmedia` version: 0.10.1
* Browser version: Firefox 103

### PR DESCRIPTION
**Pull request by zerolab**
This PR:

- fixes the summary item template
- updates the media index, list and results templates (creates legacy version)
- cleans up the rest of the template
- removes pre 2.15 code

Fixes #167
Fixes #46
Fixes #47

### CODE REVIEW

**Comment by th3hamm0r** [comment]
@zerolab UI looks good to me, but there is a new small issue:
The index view now (correctly) uses the selected collection together with the search query, this hasn't been done in previous versions.
So this is good, but it has now revealed an issue with the order of filterings done in the code:
```
2022-08-22 09:02:50 ERROR django.request: Internal Server Error: /admin/content/media/ (log.py:224)
Traceback (most recent call last):
  File "/.../lib/python3.10/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/.../lib/python3.10/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/.../lib/python3.10/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/.../lib/python3.10/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/.../lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/.../lib/python3.10/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/.../lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/.../utils/themes/decorators.py", line 14, in wrapper
    return view(request, *args, **kwargs)
  File "/.../utils/themes/decorators.py", line 23, in wrapper
    return view(request, *args, **kwargs)
  File "/.../base/urls.py", line 66, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/.../lib/python3.10/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/.../lib/python3.10/site-packages/wagtail/admin/urls/__init__.py", line 165, in wrapper
    return view_func(request, *args, **kwargs)
  File "/.../lib/python3.10/site-packages/wagtail/admin/auth.py", line 182, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/.../lib/python3.10/site-packages/wagtail/admin/auth.py", line 62, in wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/.../lib/python3.10/site-packages/django/views/decorators/vary.py", line 20, in inner_func
    response = func(*args, **kwargs)
  File "/.../src/wagtailmedia/src/wagtailmedia/views/media.py", line 61, in index
    media = media.filter(collection=current_collection)
AttributeError: 'SQLiteSearchResults' object has no attribute 'filter'
```
I first thought it is something the sqlite search engine does not support, but it also occurs with postgres.
The problem is that the `filter(...)`-calls for tags and collections are executed after `search(...)` has been called. This is done correctly in `chooser.py`, but incorrectly in `media.py`.

**Comment by th3hamm0r** [comment]
Found another issue: the tag-filter is now missing on the index view (the chooser still contains it).
It has been moved into the legacy template (see https://github.com/torchbox/wagtailmedia/pull/169/files#diff-13b761869755e60fa6d7a4a36a6ad5c26beeb55008478f9af8ee526ac2c15cb7L65), maybe for a reason?

**Comment by zerolab** [comment]
@th3hamm0r ah, good finds! I think I've accidentally dropped the tags filtering code and did not realise.

Will have a look at the filtering issue too.

**Comment by th3hamm0r** [comment]
For the tags I've tried the following, which works for me:
```
{% include "wagtailadmin/shared/collection_chooser.html" %}

{% if popular_tags %}
    <fieldset class="tagfilter">
        <legend>{% trans 'Popular Tags:' %}</legend>
        {% for tag in popular_tags %}
            {% if tag.name != current_tag %}
                <a class="button button-small button-secondary bicolor button--icon" href="{% url 'wagtailmedia:index' %}{% querystring tag=tag.name %}">{% icon name="tag" wrapped=1 %}{{ tag.name }}</a>
            {% else %}
                <a class="button button-small bicolor button--icon" href="{% url 'wagtailmedia:index' %}{% querystring tag=tag.name %}">{% icon name="tag" wrapped=1 %}{{ tag.name }}</a>
            {% endif %}
        {% endfor %}
        {% if current_tag %}
            <a class="button button-small bicolor button-secondary button--icon" href="{% url 'wagtailmedia:index' %}{% querystring tag='' %}">{% icon name="cross" wrapped=1 %}{% trans 'Clear' %}</a>
        {% endif %}
    </fieldset>
{% endif %}
```
I think you can kick the ul&li here
https://github.com/torchbox/wagtailmedia/blob/d90eeb439ca6d53d7d866497e3cdfe9884e08b86/src/wagtailmedia/templates/wagtailmedia/media/index.html#L45-L46

**Comment by zerolab** [comment]
@th3hamm0r I've pushed a fix for the missing tags, and the collection + search query filtering, including preserving the search query when changing collections

**Comment by th3hamm0r** [comment]
Did the push fail? I cannot see any new commits :grin:

**Comment by zerolab** [comment]
Ugh, it did and I didn't realise.
Some funky network error. Should all be there now

**Comment by th3hamm0r** [comment]
With my above suggestion it looks good to me. Sry, I haven't found a way to suggest code changes, which are outside the patch, hope the comment helps (I didn't want to try to push to the PR, which will probably be blocked ;).

After merging those changes it would be nice, if you could update the translation files and give me a short time to update the translations (there is just a little change at the summary item for the homepage).

**Comment by zerolab** [comment]
@th3hamm0r 7198eec makes the new strings available for translation.

Aiming to make a release tomorrow evening or Wednesday

**Pull request merged**
