### PR TITLE
Add nightly CI tests on Wagtail master with Slack notification

### PR DESCRIPTION
**Pull request by zerolab**
This PR adds nightly tests against Wagtail master. Based on https://github.com/wagtail/wagtail/wiki/Nightly-testing-of-official-plugins with the small difference of this being done via GitHub Actions

### CODE REVIEW

**Review by loicteixeira — APPROVED** [review]
Do cron scheduled actions only run of the master branch or will it run on every branch with the workflow?

Approving the PR though as it otherwise looks good to me so you can merge immediately after adding the branch restriction (if it is actually needed).

**Review by gasman — APPROVED** [review]
All looks good to me!
Re @loicteixeira's comment, the logic for when actions are triggered on different branches is a bit of a mystery to me - on a personal project I had to change the 'on' section to

    on:
      push:
        branches: [ master ]
      pull_request:
        branches: [ master ]

to stop it triggering twice on every commit, but I had no such problems on the Wagtail repo...

**Comment by zerolab** [comment]
@loicteixeira  @gasman 

>Scheduled workflows run on the latest commit on the default or base branch.
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule

**Comment by zerolab** [comment]
Thank you both!

**Pull request merged**
