### PR TITLE
Fix nightly test for Wagtail 6.3 / Django 5.1

### PR DESCRIPTION
**Pull request by gasman**
* update Postgres to v15
* replace `assertQuerysetEqual` with `assertQuerySetEqual`

### CODE REVIEW

**Comment by zerolab** [comment]
@gasman https://github.com/torchbox/wagtailmedia/blob/main/.github/workflows/test.yml#L65-L68 needs `if-no-files-found: ignore` and we're good to go

**Comment by gasman** [comment]
@zerolab Where does that need to be added? (The lines you link to already have it...)

**Comment by zerolab** [comment]
gah, copied the wrong line. It needs `include-hidden-files: true`

**Comment by gasman** [comment]
Now rebased to remove the temporary "run nightly tests on PR" addition - https://github.com/torchbox/wagtailmedia/actions/runs/11663518640/job/32472102881 shows the nightly run completing successfully.

**Pull request merged**
