### PR TITLE
django.po

### PR DESCRIPTION
**Pull request by Dannykey**
venv\Lib\site-packages\wagtailmedia\locale\zh_Hans\LC_MESSAGES

### CODE REVIEW

**Review by thibaudcolas — CHANGES_REQUESTED** [review]
Hey @Dannykey, thank you for this!

This looks great, I’ll need to figure out how to review a language I don’t know, if at all.

I think the file needs to be moved to:

```
wagtailmedia/wagtailmedia/locale/zh_CN/LC_MESSAGES/django.po
```

to match the structure expected by Django?

**Comment by BrianXu20** [comment]
line：268
msgid "Uploaded"
msgstr "上传"
上传 means upload, but uploaded should be 已上传

**Comment by BrianXu20** [comment]
and 使用 means use , Usage often refers to 用途

**Comment by BrianXu20** [comment]
line:332
msgid "Media file '{0}' added."
msgstr "媒体文件 '{0}' 添加" should be msgstr "媒体文件 '{0}' 已添加"

**Pull request merged**
